# pyproject.toml
[tool.poetry]
name = "ltto_edmd"
version = "0.1.0"
description = "Low thrust trajectory optimization with EDMD"
authors = ["TAEUK KANG <kuty1210@naver.com>"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
numpy = "^1.26"
scipy = "^1.12"
matplotlib = "^3.8"
pandas = "^2.1"
tqdm = "^4.66"
openpyxl = "^3.1.5"
cupy-cuda12x = "13.6.0"
torch = { version = "2.7.*", source = "pytorch-cu128" }
torchvision = { version = "0.22.*", source = "pytorch-cu128" }
torchaudio = { version = "2.7.*", source = "pytorch-cu128" }

[[tool.poetry.source]]
name = "pypi"
priority = "primary"

[[tool.poetry.source]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"